services:
  nginx:
    container_name: daodin_nginx
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      CERTBOT_EMAIL: $CERTBOT_EMAIL
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - daodin

  app:
    container_name: daodin_node
    image: node:latest
    command: sh -c "cd /app && mkdir -p static && cd /app/Backend && npm install pm2 -g && npm install && pm2 start index.js && pm2 start wss_index.js && pm2 save && pm2 startup && pm2 logs "
    init: true
    restart: always
    volumes:
      - ./Backend:/app/Backend
      - picture_storage:/app/static
      - node_modules:/app/Backend/node_modules
      - ./default_images:/app/default_images

    ports:
      - "3000:3000"
      - "3001:3001"
    expose:
      - "3000"
      - "3001"
    networks:
      - daodin
    depends_on:
      - rabbitmq

  python:
    container_name: daodin_python
    image: python:3.11
    command: sh -c "cd /app/NLP_Model && pip install --upgrade pip && pip install -r requirements.txt && python api.py"
    init: true
    restart: always
    volumes:
      - ./NLP_Model:/app/NLP_Model
      - python-packages:/lib/python3.11/site-packages
    networks:
      - daodin
    ports:
      - "5000:5000"
    expose:
      - "5000"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    hostname: rabbitmq
    init: true
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - daodin
  redis:
    container_name: daodin_redis
    image: redis:alpine
    init: true
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - daodin

volumes:
  rabbitmq_data:
  node_modules:
  picture_storage:
  nginx_secrets:
  python-packages:
  redis_data:


networks:
  daodin:
    driver: bridge
